# Generated by Django 5.1.1 on 2024-09-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_purchasebooks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasebooks',
            options={'verbose_name_plural': 'puchases books'},
        ),
    ]
